.dockerignore
.env.example
.gitignore
Dockerfile
README.md
app.yml
jest.config.js
package-lock.json
package.json
src/index.ts
test/fixtures/issues.opened.json
test/index.test.ts
tsconfig.json

Following PR was created using `create-probot-app`, which generates initial Probot app project (more information can be found [here](https://probot.github.io/docs/development/#generating-a-new-app)). This generated project was edited so it suits our purposes (e.g. generated LICENSE, CODE OF CONDUCT and other files where ommited, instructions how to run this app were taken from generated README and added to ours).
Resolves #4

feat: Bootstrap the repostiory for a Github App controller

---

architecture.md

Quick outline of the initial flow we would like to support.

feat(architecture): Initial architecture draft

---

pipelines/base/peribolos-run.yaml

Part of: #10 
This is task for running peribolos. Task gets token from a secret and uses it to run peribolos.

feat: Add task for running peribolos on push event

---

manifests/deployment-config.yaml
manifests/kustomization.yaml
manifests/route.yaml
manifests/service-account.yaml
manifests/service.yaml
package-lock.json
package.json
src/index.ts

Generate Token for each install and store them as k8 secrets
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>
Related-to: https://github.com/open-services-group/peribolos-as-a-service/issues/6

Generate Token for each install and store them as k8 secrets

---

pipelines/base/config-dump.yaml

Resolves part of #9 
Workspace `secret-data` is filled using a secret as discussed in #6.

feat(dump-config): Create task

---

pipelines/base/config-dump.yaml
pipelines/base/peribolos-run.yaml

rename config file to peribolos.yaml

---

package-lock.json
src/index.ts

Update app installation token on secret every 40 mins
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>
Related-to: https://github.com/open-services-group/peribolos-as-a-service/issues/7

Update app installation token on secret

---

src/index.ts

Resolves: #10 
Handles push event send to controller. Creates a TaskRun which runs Task specified in #20.
~~Still needs tests to be implemented.~~ I am gonna split this and do the tests later down the line.

feat: Add push event controller

---

.aicoe-ci.yaml
README.md
manifests/deployment-config.yaml
manifests/imagestream.yaml
manifests/kustomization.yaml

https://github.com/open-services-group/peribolos-as-a-service/issues/33

add imagestream for controller image

---

src/index.ts

add webhook delete
closes https://github.com/open-services-group/peribolos-as-a-service/issues/8

User unsubscribe

---

src/index.ts

fix: Fix namespace variable name in push event

---

README.md

included dev setup docs
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>
Related-to: https://github.com/open-services-group/peribolos-as-a-service/issues/22

included dev setup docs

---

.pre-commit-config.yaml
jest.config.js
src/app.ts
test/index.test.ts

chore: Use prettier pre-commit hook as well

---

manifests/base/controller/deployment.yaml

fix: Deployment CPU request is wrong format

---

manifests/base/controller/deployment.yaml

:hankey: Broke the build via #100.. sigh

fix: Deployment CPU request is wrong format [2]

---

manifests/base/controller/route.yaml

fix: Use https route

---

.github/workflows/promote.yaml

chore(ci): Fix promote workflow

---

manifests/base/tasks/dump-config.yaml
src/app.ts
src/probotOnKube.ts
tsconfig.json

fix: Probot on kube doesn't work in prod builds

---

manifests/base/controller/role.yaml

fix(controller): Role to allow secret deletion

---

ACKNOWLEDGMENTS.md
CONTRIBUTORS.md
README.md

Acknowledge our contributors and make the environment more visible.

chore: Add acknowledgments, contributors, deployment links to readme

---

.github/workflows/push.yaml
.github/workflows/release.yaml
CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md
SECURITY.md
SUPPORT.md
manifests/base/kustomization.yaml
manifests/overlays/prod/kustomization.yaml
manifests/overlays/stage/kustomization.yaml
package-lock.json
package.json
src/app.ts

Related to: https://github.com/open-services-group/community/issues/231

feat: Relocate Probot repositories to Operate First

---

src/app.ts

Resolves: https://github.com/operate-first/peribolos-as-a-service/issues/164

fix: wrapOperationWithMetrics status label

---

manifests/base/kustomization.yaml
manifests/base/monitoring/kustomization.yaml
manifests/base/monitoring/prometheusrule.yaml

Resolves: https://github.com/operate-first/peribolos-as-a-service/issues/165

feat: Add basic prometheus alerts

---

README.md

I've discovered some nonsense in the README, so I'm fixing it.

docs: Fix README typos

---

package-lock.json
package.json
src/app.ts
src/cache.ts

Resolves: https://github.com/operate-first/peribolos-as-a-service/issues/167
Further improvement on the `wrapOperationWithMetrics` are required, will be in a follow up PR.

feat: Add OCP link to check

---

manifests/base/tasks/run.yaml

Added `--fix-org-members` option

feat: Added --fix-org-members

---

.github/renovate.json

SSIA
Change from 3 days long grace period to 1 day. @goern keeps overriding that check anyways 😛 😄 
Same as https://github.com/operate-first/probot-template/pull/108

chore: tune down stability-days
